# Generated by Django 6.0 on 2025-12-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Код закладу в ЄДЕБО')),
                ('title', models.CharField(max_length=100, verbose_name='Назва університету')),
                ('ownership', models.CharField(max_length=8, verbose_name='Форма власності')),
                ('rector', models.CharField(max_length=100, verbose_name='Ім\\`я ректора')),
                ('location', models.TextField(verbose_name='Місцезнаходження')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон/факс')),
                ('email', models.CharField(max_length=50, verbose_name='Електронна пошта')),
                ('website', models.CharField(max_length=120, verbose_name='Вебсайт університету')),
                ('military_department', models.CharField(max_length=3, verbose_name='Чи є військова кафедра')),
                ('grants', models.CharField(max_length=3, verbose_name='Чи бере заклад участь в програмі державних грантів на здобуття вищої освіти')),
                ('year', models.CharField(max_length=4, verbose_name='Рік заснування')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
