# Generated by Django 6.0 on 2025-12-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Університет', 'verbose_name_plural': 'Університети'},
        ),
        migrations.AlterField(
            model_name='university',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='Телефон/факс'),
        ),
        migrations.AlterField(
            model_name='university',
            name='rector',
            field=models.CharField(max_length=100, verbose_name='Ім`я ректора'),
        ),
        migrations.AlterField(
            model_name='university',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Назва університету'),
        ),
    ]
