# Generated by Django 6.0 on 2026-01-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_university_options_alter_university_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='ownership',
            field=models.CharField(max_length=10, verbose_name='Форма власності'),
        ),
        migrations.AlterField(
            model_name='university',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон/факс'),
        ),
    ]
